version: '3.7'

services:
    zookeeper:
        restart: always
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"
    my-cluster:
        restart: always
        image: wurstmeister/kafka:2.11-1.1.1
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        depends_on:
            - zookeeper
    cartCache:
        image: redis:latest
        container_name: cartCache
        command: redis-server --save 20 1 --loglevel warning
        restart: always
        ports:
            - 6379:6379
        volumes:
            - /data
    coolstoreDB:
        image: mongo:latest
        container_name: coolstoreDB
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: Coolstore
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # cartservice:
    #     depends_on:
    #         - coolstoreDB
    #         - cartCache
    #         - my-cluster
    #     build: ../cart-service
    #     ports:
    #         - 7074:7074
    #     environment:
    #         - REDIS_SERVICE_HOST=cartCache
    #         - KAFKA_SERVICE_HOST=my-cluster
    inventoryservice:
        depends_on:
            - coolstoreDB
        build: ../inventory-service
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - COOLSTORE_DB_SERVICE_HOST=coolstoreDB
    catalogservice:
        depends_on:
            - coolstoreDB
        build: ../catalog-service
        restart: unless-stopped
        ports:
            - 7072:7072
        environment:
            - COOLSTORE_DB_SERVICE_HOST=coolstoreDB
            - INVERNTORY_SERVICE_HOST=inventoryservice