version: '3.7'

services:
    cartCache:
        image: redis:latest
        container_name: cartCache
        command: redis-server --save 20 1 --loglevel warning
        restart: always
        ports:
            - 6379:6379
        volumes:
            - /data
    coolstoreDB:
        image: mongo:latest
        container_name: coolstoreDB
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: Coolstore
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    inventoryservice:
        depends_on:
            - coolstoreDB
        build: ../inventory-service
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - COOLSTORE_DB_SERVICE_HOST=coolstoreDB
    catalogservice:
        depends_on:
            - coolstoreDB
        build: ../catalog-service
        restart: unless-stopped
        ports:
            - 7072:7072
        environment:
            - COOLSTORE_DB_SERVICE_HOST=coolstoreDB
            - INVERNTORY_SERVICE_HOST=inventoryservice
