kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: coolstore-dev
  labels:
    app: redis
    app.openshift.io/runtime: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        deployment: redis
    spec:
      volumes:
        - name: redis-1
          emptyDir: {}
      containers:
        - name: redis
          image: docker.io/redis:latest
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: redis-1
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env: []
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
