apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: coolstore-dev
spec:
  selector:
    deployment: redis
  ports:
    - name: 6379-tcp
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
